### ISSUE TITLE
System crashes and settings are lost after new bed mesh is saved. 

### ISSUE THREAD

**Issue by bigmick110** [classicrocker883/MRiscoCProUI#112]
### Did you test the latest release build?

No, but I will try it!

### Bug Description

I had a go at installing Klipper and couldn't get it to work so I'm back for good !! I hope you guys keep going for as long as you can !! It's very much appreciated... I've also had an issue(Now I've reinstalled everthing back the way it was - Dec2023 build) with the system crashing when I go to save a new bed mesh and losing all my settings...It will run the bed mesh fine but as soon as I hit the save button it crashes/restarts and all my settings are lost. I haven't tried any Jan-Fed builds yet as I wasn't sure what was good to go for the H32 and what was "Pre release". I'm still looking so if I find something I think is an update I'll give it a go. I have a brand new N32 board that I used while playing around with Klipper.... Would I be better off in the long term to swap these over ?? Thoughts ?? 

### Printer Model

Voxelab Aquila

### Model Type

X2

### Your Mainboard

Aquila HC32

### Add-ons that could be involved

Sprite/BLT 

### ProUI?

ProUI

### Bed Leveling

BLT - BL Touch Bilinear mesh

### Did you include your own configuration files?

- [ ] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by classicrocker883** [comment]
the N32 is much better regarding issues with H32. I'm not so sure the issue you described if it has to do with the ProUI extra features or not. you can try _-UBL_ or _-NoPro_ version which I [just uploaded here](https://github.com/classicrocker883/MRiscoCProUI/releases/tag/2.1.3f-HC32-2-1)

I have also uploaded some other [UI for HC32 for testing](https://github.com/classicrocker883/MRiscoCProUI/releases/tag/2.1.3f-HC32-UI).

regarding the N32 that is your best bet since there are still some bugs to take care of the H boards.

I have been working on a new release for this month and will be uploading that build soon

**Comment by auntyridge** [comment]
I have the same issue with the HC32 on all versions however by chance I found that if I used Bed Mesh from the Toolbar I can save the mesh without crashing, it only crashes when I use it from the Level menu. Hope this helps
