### ISSUE TITLE
[BUG] after homing, fast movements with skipped steps

### ISSUE THREAD

**Issue by Weresk** [classicrocker883/MRiscoCProUI#149]
### Did you test the latest release build?

Yes, and the problem still exists.

### Bug Description

1) Flash new firmware  Version: 2.1.3f-8-1 (on the previous Version: 2.1.3f-7 all OK)
2) Start printing something and after homing movements, maybe they are called travel movements, very fast head jerking with skipping steps (as if huge speeds were set)
[Configuration.zip](https://github.com/user-attachments/files/16741379/Configuration.zip)

### Printer Model

Voxelab Aquila

### Your Mainboard

Aquila GD32

### ProUI-EX | Extra Features?

Yes

### Bed Leveling

MM - Manual Mesh Bed Leveling

### Did you include your own configuration files?

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by classicrocker883** [comment]
does this happen on any particular axis?
I did bump the `MANUAL_FEEDRATE` for Z from 8*60 to 10*60, but according to your Configs that isn't the case.  
I also see you have `OLD_ADAPTIVE_MULTISTEPPING` disabled, and `TMC2208` instead of `TMC2208_STANDALONE` for E0.

it could be also your Acceleration/Jerk settings. could you try using one of the prebuilt firmwares for your board? seeing you use Creality V4 (I assume, if not what is it?), look for 422 in the **.bin** - thats the same. or here is one of the Ender-3 V2 builds https://github.com/classicrocker883/MRiscoCProUI/releases/tag/2.1.3f-8-ender3-1

**Comment by classicrocker883** [comment]
in **settings.cpp**, look for 
```y
  //
  // HAS_MOTOR_CURRENT_PWM
  //
  #if HAS_MOTOR_CURRENT
  
  [...]

      //
      // Motor Current PWM
      //
      #if HAS_MOTOR_CURRENT
```
or anything that has `#if HAS_MOTOR_CURRENT` + it's `#endif` remove those because there is no such `HAS_MOTOR_CURRENT` that is a mistake.

**Comment by classicrocker883** [comment]
let me know if you still have an issue with the new release

**Comment by classicrocker883** [comment]
id like to say this was related to the same issue, closing
