### ISSUE TITLE
Not a bug, but question: Should I select Marlin 2 in PrusaSlicer

### ISSUE THREAD

**Issue by patrickmac110** [classicrocker883/MRiscoCProUI#39]
I just upgraded from stock firmware after installing new hotend and CR-Touch to your newest release, the GD32_BLT-ProUI-MPC.bin for my Voxelab Aquila. I was wondering if this is a fork of Marlin 2 or not?
Maybe a dumb question.

**Comment by classicrocker883** [comment]
thats a valid question. I wondered the same thing, it appears it may depend on what printer you have selected for settings because changing from Marlin 2 to any one of the other options changes the beginning Gcode - as it starts printing. from Marlin (legacy) to Marlin 2, it appears there aren't any differences, and if there were, its not significant enough to really change much. 

long story short, Marlin 2 is what you should use, since its based on the current most upto date Marlin `bugfix-2.1.x` branch.
