### ISSUE TITLE
newer builds missing bed tramming option in prepare menu

### ISSUE THREAD

**Issue by zerog2k** [classicrocker883/MRiscoCProUI#45]
newer builds are missing `bed tramming` option from `prepare` menu

previous build has this menu 
N32-MM_ProUI.bin with version date 20230119

current build does not have `bed tramming` in prepare (or anywhere else I can find it)
N32-MM-ProUI.bin with version date 20230517

**Comment by zerog2k** [comment]
I assume for Voxelab Aquila X2, it should be coming from here:
https://github.com/classicrocker883/MriscocProUI/blame/3fc2d945cd190d92e8946eb95ed770debffd8be1/configurations/Voxelab%20Aquila/MM/Configuration.h#L2185

But looking over this, it seems like bed tramming has (at least as far back as Jan 2023) been disabled
I don't understand then how I have bed tramming enabled on this January build:
https://github.com/classicrocker883/MriscocProUI/releases/download/2.1.3b/N32-MM_ProUI.bin
from this release:
https://github.com/classicrocker883/MriscocProUI/releases/tag/2.1.3b

**Comment by zerog2k** [comment]
Actually looking through the configs in this repo I see a mix and match of LCD_BED_TRAMMING turned on and off
why would this be? I would think _all_ printers should have bed tramming wizard at least enabled in menus for initial rough leveling (regardless of fine tuning method: manual mesh, UBL, BL-touch, etc)?
I can submit a PR for enabling them all, if this sounds sane.

**Comment by classicrocker883** [comment]
that would be my mistake when compiling, i must have forgot to reneable after changing the code or testing.

everything should be normal working now. 

i made a quick compilation of the [new files and versions here](https://github.com/classicrocker883/MriscocProUI/releases/tag/2.1.3d)

let me know how it goes, and if you have the HC32 / H32 board
it is [located here](https://github.com/classicrocker883/MriscocProUI/releases/tag/2.1.3d-hc)

**Comment by classicrocker883** [comment]
so why i havent enabled LCD_BED_TRAMMING is because it really isn't a useable option/feature. the tramming wizard is already enabled. Mriscoc had changed the values to under `#if ENABLED(LCD_BED_TRAMMING)` , i didn't change the code from that update instead kept it more or less the same, however you can have that enabled and use those values there if you wanted to, but then you wont be able to use the editable `BED_SCREW_INSET` corner position. basically youre able to change those values in advanced settings menu to adjust where each corner of the bed is. rather than if LCD_BED_TRAMMING is enabled you dont get that option.
