### ISSUE TITLE
difference between the versions

### ISSUE THREAD

**Issue by 314ru** [classicrocker883/MRiscoCProUI#5]
what is the difference between the versions: RC, RC_maple, RE?

**Comment by classicrocker883** [comment]
@314ru sorry for late reply, i overlooked this comment.

the difference is RC uses less memory, and RE has more. that deals with the type of chip. like STM32F103RET6 is a common chip in creality boards. i think the Ender S1 uses the RC version.

maple is just a sort of version with parameters. i dont know a whole bunch but Aquila boards like to run on _maple. creality boards I have tested and they can run on either with or without _maple.

i think its better without maple because maple is depreciating.
