### ISSUE TITLE
linear advance on aquila x2[FR] 

### ISSUE THREAD

**Issue by PolcovnicGauss** [classicrocker883/MRiscoCProUI#63]
### Is your feature request related to a problem? Please describe.

The rest of the firmware does not work properly, I need a simple but stable firmware without bells and whistles

### Are you looking for hardware support?

Aquila x2 main board HC32

### Describe the feature you want

Can you compile the most simple and stable firmware, with a simple interface for aquila x2, so that it has linear advance?

**Comment by classicrocker883** [comment]
yes as I mentioned in the other post I am working to getting the JyersUI to work for the HC32. it's the NoPro essential but known to be stable.

not to mention it will be to the most upto date Marlin version. look forward to seeing that sometime this week.

**Comment by classicrocker883** [comment]
I want to say that Linear Advance **should be enabled ** for the HC32.

I think however there was a slight mistake with the option not showing up. However you can still set the value using the M900 gcode.

**Comment by PolcovnicGauss** [comment]
there is a problem with linear advance again, it seems to work, but when I try to print the calibration code from here https://marlinfw.org/tools/lin_advance/k-factor.html, every time the K-factor increases, the printing speed drops, This can be seen even visually, what could be the problem?

**Comment by classicrocker883** [comment]
> there is a problem with linear advance again, it seems to work, but when I try to print the calibration code from here https://marlinfw.org/tools/lin_advance/k-factor.html, every time the K-factor increases, the printing speed drops, This can be seen even visually, what could be the problem?

I couldn't tell you. there has been some updates, and I made a new release with them, you can try the new version and see if that is any better. otherwise, maybe post the issue over at MarlinFirmware? because the code over here shouldnt be any different. I can go through and make sure there isnt anything that pops out.

one thing I can say is I had enabled `OLD_ADAPTIVE_MULTISTEPPING` for the Aquila boards because users were getting issues with stepper motors making noise, and having this enabled helped. it could be that with updates this may not be needed anymore or it could be somehow interfering with Linear Advance. another thing is Adaptive Step Smoothing in Control > Motion settings. you can try disabling this and see if that changes.

if you want, I can compile a version without `OLD_ADAPTIVE_MULTISTEPPING` and see if that makes a difference.
